sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t superset .
      - docker images
      - docker tag superset $DOCKER_USERNAME/superset:0.29.0rc7
      - docker push $DOCKER_USERNAME/superset:0.29.0rc7
